USE [BARandResto]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BAR_LOGIN](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRSTNAME] [varchar](20) NOT NULL,
	[LASTNAME] [varchar](20) NOT NULL	
PRIMARY KEY (ID)
)